### ISSUE TITLE
When editing a Post, it's not giving an option to edit the Post Title

### ISSUE THREAD

**Issue by ghost** [laurencedawson/sync-for-lemmy#298] opened 2023-08-12 23:46 UTC
**Describe the bug**  
In the Lemmy web version, and the Jerboa for Lemmy app, it gives you an option to edit the Post Title. In Sync, when editing a post, it does not give that option. 

**Steps to Reproduce**  
1. Create a Post
2. Click on the three dots on the post, and click Edit
3. There is not an option to edit the Post Title

**Expected behavior**  
When editing a post, would like to be able to also edit the Post Title

**Smartphone (please complete the following information):**
 - Device: Samsung A53 5G
 - Android: 13
 - Sync version: v23.08.12-23:05 (29)
 - Sync variant: Beta

**Additional context**

**Comment by gazelle8844** [comment] 2023-08-13 01:04
I just realized, that this issue that I submitted #298, is basically a duplicate of Issue #297-  Post Editing doesn't let you change anything except text

**Comment by laurencedawson** [comment] 2024-03-10 16:52
Added for the next release.

**Closed by laurencedawson** 2024-03-10 16:52 UTC
Labels: enhancement
