### ISSUE TITLE
Crash when opening Messaging in Settings

### ISSUE THREAD

**Issue by kontrastylez** [laurencedawson/sync-for-lemmy#65] opened 2023-07-25 06:28 UTC
**Describe the bug**  
When Messaging in Settings is clicked, the app crashes.

**Steps to Reproduce**  
1. Go to 'Settings'
2. Click on 'Messaging'
3. App crashes

**Expected behavior**  
Not crashing.

**Smartphone (please complete the following information):**
 - Device: Pixel 6a and Pixel Tablet
 - Android: 13
 - Sync version: 23.07.25-01:05 (9)

**Comment by Coffee-Viking** [comment] 2023-07-25 06:40
OnePlus 10 Pro, Android 12: Closes the settings and reloads the frontpage. No direct crash but certainly unwanted behavior.

**Comment by Ictinus** [comment] 2023-07-25 08:32
Duplicate of #64

**Comment by laurencedawson** [comment] 2023-07-25 15:07
Fixed

**Closed by laurencedawson** 2023-07-25 15:07 UTC
