### ISSUE TITLE
Username of non active account in account picker is empty

### ISSUE THREAD

**Issue by dallyh** [laurencedawson/sync-for-lemmy#492] opened 2024-03-11 21:06 UTC
**Describe the bug**  
As the title says - username of non active account in account picker is empty 

**Steps to Reproduce**  
1. Log on to multiple accounts
2. Open account picker
3. Check usernames

**Expected behavior**  
Usernames should be visible.

**Screenshots**  
![Screenshot_20240311_215919_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/6968534/866fa7b6-e5c6-4358-bf4f-7c2678f5f12d)

![Screenshot_20240311_215932_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/6968534/4f44b658-04bb-41fb-9c91-16279d5f5a78)

**Smartphone**
 - Device: Galaxy S22
 - Android: 14 - OneUI 6
 - Sync version: Visible on screenshots
 - Sync variant: Pro

**Comment by corylowry12** [comment] 2024-03-12 00:00
Duplicate of #451

**Closed** 2024-03-13 16:03 UTC

**Comment by dallyh** [comment] 2024-03-19 07:53
@laurencedawson 

I would like to reopen this as on the latest beta (109)  this issue is still present. 

**Device information**

    Sync version: v24.03.12-19:36    
    Sync flavor: googlePlay    
    
    Ultra user: false    
    View type: Slides    
    Push enabled: false    
    
    Device: r0s    
    Model: samsung SM-S901B    
    Android: 14

![Screenshot_20240319_084943_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/6968534/efacb788-9a90-4422-a08e-60e12370022b)

Also if I want to remove the non active account it is not shown.

![Screenshot_20240319_085244_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/6968534/9da2d2bf-e804-4745-b0d2-3766011f739c)
