### ISSUE TITLE
Opening 'More Actions' when in a post crashes the app

### ISSUE THREAD

**Issue by junoneko** [laurencedawson/sync-for-lemmy#351] opened 2023-08-25 04:50 UTC
**Describe the bug**  
Opening 'More Actions' when in a post makes the app quit immediately

**Steps to Reproduce**  
1. Go open any post
2. Click on 'More Actions' on the top right
3. Sync closes immediately

**Expected behavior**  
The 'More Actions' menu to drop down like when you're not in a post

**Screenshots**  
None

**Smartphone (please complete the following information):**
 - Device: POCO F1
 - Android: 13
 - Sync version: v23.08.23-18:29 (Beta 34)
 - Sync variant: Free

**Additional context**  
I restored a backup from Sync for Reddit for an account but it also seems to crash when in anonymous view(stock settings). Also has been happening since before Beta 34.

**Comment by DaniFold06** [comment] 2023-08-25 04:59
duplicate of #210

**Comment by laurencedawson** [comment] 2023-09-01 00:21
Fixed in todays release.

**Closed by laurencedawson** 2023-09-01 00:21 UTC
Labels: bug
