### ISSUE TITLE
Separate Downvote & Upvote Scores + Vote Total in Profile

### ISSUE THREAD

**Issue by Runite-Rain** [laurencedawson/sync-for-lemmy#249] opened 2023-08-04 20:57 UTC
Option to toggle Upvotes vs Downvotes for each post and comment.
Should also see total points on particular instance on Profile Page (total points, total comments, total posts), like Voyager. Moreover, should have option to decide which default landing page (posts, comments, saved, etc) should be on Profile.

**Comment by pwd-github** [comment] 2023-08-06 20:32
Dupe of https://github.com/laurencedawson/sync-for-lemmy/issues/128

**Closed** 2023-08-22 23:49 UTC
