### ISSUE TITLE
Oneui 5 navigation bar semi transparent

### ISSUE THREAD

**Issue by corylowry12** [laurencedawson/sync-for-lemmy#80] opened 2023-07-25 11:45 UTC
**Describe the bug**  

**Steps to Reproduce**  
1. Open the app 
2. See the navigation bar is the wrong color

**Expected behavior**  

- To be the same color as the bottom nav bar 

**Screenshots**  

![Screenshot_20230724_165818_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/8837361/62534d98-a202-4736-96ad-2e90185f1829)

**Smartphone (please complete the following information):**
 - Device: S22 ultra
 - Android: 13, oneui 5.1
 - Sync version: v23.07.25-01:05

**Comment by cedeel** [comment] 2023-07-25 15:39
The bug also occurs in v23.07.25-16:32

**Comment by atrctr** [comment] 2023-07-25 16:32
Reproduced on:
- Sync v23.07.25-16:32
- Device: Galaxy Tab S6 Lite 2022
- System: Android 13, OneUI 5.1

**Comment by laurencedawson** [comment] 2023-07-25 17:05
Dang cant reproduce at all

**Comment by laurencedawson** [comment] 2023-09-21 19:29
Confirmed on discord to be fixed on the latest one UI 6 beta. 

Thanks for the update @corylowry12

**Closed by laurencedawson** 2023-09-21 19:29 UTC
Labels: bug, blocked
