### ISSUE TITLE
Comment section not displaying properly when sorted by Top

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/sync-for-lemmy#133] opened 2023-07-27 16:42 UTC
**Describe the bug**  
Comments on some posts display improperly when sorted by top.

**Steps to Reproduce**  
1. Go to [this link](https://lemmy.world/post/2231631)

**Expected behavior**  
Comments should display with the proper hierarchy, for example when sorted by Hot.

**Screenshots**  

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A14 5G
 - Android: 13
 - Sync version: v23.07.27-13:47 (18)

**Comment by laurencedawson** [comment] 2023-07-27 17:11
What do you mean properly? Screenshot if possible.

**Comment by machinator2** [comment] 2023-07-27 17:45
![Screenshot_20230727_124436_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/11968133/db65105e-6766-4f34-89a0-1d93d07b4ba7)

**Comment by spoon247** [comment] 2023-07-28 15:01
Few more examples

https://i.postimg.cc/vTMW7q2Y/Screenshot-20230728-175251-Sync.jpg

https://i.postimg.cc/QCbcfQvp/Screenshot-20230728-175453-Sync.jpg

**Comment by chloyster** [comment] 2023-07-31 15:04
Yeah this has been an issue for me too. It seems like when the child comment has more votes than the parent comment is when things get screwy.

**Comment by roelhospel** [comment] 2023-08-02 17:37
I've encountered this bug as well

# Description

When viewing the comments under a post, and sorting these comments by "top", this causes some odd sorting behaviour.
Comments are seemingly not displayed in the proper order.

I've encountered this bug on the following post: https://lemmy.world/comment/1958306

# Steps to reproduce

1. Open the post in the Sync for Lemmy app
2. Sort the comments by Top (via the option in the top right of the app)
3. On the first comment (which in my case was https://lemmy.world/comment/1958306), there is a button to "View more (5)"
4. Click on this button

# Observed Behaviour

As shows in the appended screenshots, the comments that show up are completely out of order. 
The first comment is immediately 5 levels deep, and has one of the lower scores. Some higher scoring comments are also lower than the lower scoring comments

It's also noteworthy that the "View more (5)" button is above the other comment. I feel like that should be below the other comments

# Expected Behaviour

A reaction to a comment should be below that comment, followed by a reaction to a reaction.
When sorting by top, the highest scoring comments should be above the lower scoring comments

Maybe the "View more (5)" button should be below the other comments? This is just my expectation though.

# System Specs

Google Pixel 6a, running Android 13
Running version v23.08.01-20:30 (24) of the app

**Comment by roelhospel** [comment] 2023-08-02 17:38
# Screenshots
![Screenshot_20230802-191030](https://github.com/laurencedawson/sync-for-lemmy/assets/10463997/a6cd95c9-861e-4441-856c-eca5d0c72402)

![Screenshot_20230802-191039](https://github.com/laurencedawson/sync-for-lemmy/assets/10463997/359e983e-3f97-4066-9038-daf5cd01b1f5)

**Comment by Madbrad200** [comment] 2023-08-03 01:46
Nobody seems to have mentioned it, so I shall add: this also happens to me under "Hot" sorting. "New" sort displays proper parent/child comment relationships, whereas under "Hot" or "Top", child comments are displayed under the wrong parents.

"Old" sort results in 403, which is probably an unrelated issue.

**Comment by nalmada** [comment] 2023-08-03 19:51
> Nobody seems to have mentioned it, so I shall add: this also happens to me under "Hot" sorting. "New" sort displays proper parent/child comment relationships, whereas under "Hot" or "Top", child comments are displayed under the wrong parents.
> 
> "Old" sort results in 403, which is probably an unrelated issue.

depends of the instance

- on lemmy.wold. Old results in 403 errors
- on lemm.ee. Old results on "There are no comments"

**Comment by CMahaff** [comment] 2023-08-04 10:05
Another thread with examples - at time of writing I see misordered comments for Hot, but also Top and New if you click "View More" - https://lemmy.world/post/2615664

Don't know if #233 is a separate issue or related to this issue - my view more is "working" in that it loads comments, but then they are totally in the wrong place for every sort order. See example link above.

**Comment by chloyster** [comment] 2023-08-04 21:23
Potentially related PR here 

https://github.com/LemmyNet/lemmy/pull/3823

**Comment by pwd-github** [comment] 2023-08-10 12:08
This should be fixed by 0.18.4

**Comment by pwd-github** [comment] 2023-08-10 12:44
I'm unsure how it works, but it could require your home instance to be on 0.18.4

**Comment by AnneKok** [comment] 2023-08-18 08:03
For me it's the above issue and also replies showing up under the wrong comment / not under their actual parent.

For instance post https://feddit.de/post/2640526

This is what it looks like on Sync for Lemmy on Android with comments sorted by Top (my version in app info is listed as v23.8.12-23:05 (29)) 

![Screenshot_20230818_095542_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/7063684/257d7e41-7695-44d1-9759-e517c4a611a0)

The comment under View More is a reply to a completely different parent which is shown BELOW it:

![Screenshot_20230818_095551_Sync](https://github.com/laurencedawson/sync-for-lemmy/assets/7063684/b9ffefb9-a417-4d2c-8a16-88cbc618f4d7)

Here again some of the comments shown as replies are actually replies to another top-level comment.

**Comment by laurencedawson** [comment] 2023-08-24 23:49
Fixed for the next release.

**Closed by laurencedawson** 2023-08-24 23:49 UTC
Labels: bug
