### ISSUE TITLE
Thumbnails fail to load for XKCD link posts

### ISSUE THREAD

**Issue by geominorai** [laurencedawson/sync-for-lemmy#85] opened 2023-07-25 12:57 UTC
**Describe the bug**  

Link posts with an XKCD URL fail to show a thumbnail in both the feed and comment pages.  Glide failed to grab the image.

**Steps to Reproduce**  
1. Go to https://lemmy.world/post/2085432
2. See error.

**Expected behavior**  
The thumbnail image provided by the Lemmy API should have been shown.

**Screenshots**  

<img src="https://cdn.discordapp.com/attachments/1120741766820286464/1133373028810629170/Screenshot_20230725-051940_Sync.png" width=250 />

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - Android: 10
 - Sync version: v23.07.25-13:31 (10)
 - Sync variant: Beta

**Additional context**  

The thumbnail URL is provided in the API response: https://lemmy.world/api/v3/comment/list?post_id=2085432&sort=Hot:

```json
 "post": {
        "id": 2085432,
        "name": "Opinions: What is a movie you genuinely like, that is rated below 60% on rotten tomatoes?",
        "url": "https://xkcd.com/2184/",
        "body": "Inspired by the linked XKCD. Using 60% instead of 50% because that's an easy filter to apply on rottentomatoes.\n\nI'll go first: I think \"Sherlock Holmes: A game of Shadows\" was awesome, from the plot to the characters ,and especially how they used screen-play to highlight how Sherlocks head works in these absurd ways. ",
        "creator_id": 233933,
        "community_id": 3106,
        "removed": false,
        "locked": false,
        "published": "2023-07-24T12:11:08.663588",
        "deleted": false,
        "nsfw": false,
        "embed_title": "Unpopular Opinions",
        "thumbnail_url": "https://lemmy.world/pictrs/image/494f3c98-4373-463e-aed9-430e1bc0900a.png",
        "ap_id": "https://lemmy.world/post/2085432",
        "local": true,
        "language_id": 0,
        "featured_community": false,
        "featured_local": false
      },
```

<img src="https://lemmy.world/pictrs/image/494f3c98-4373-463e-aed9-430e1bc0900a.png" width=250 />

**Comment by pwd-github** [comment] 2023-07-25 13:02
Dupe of #76 ?

**Comment by geominorai** [comment] 2023-07-25 18:48
> Dupe of #76 ?

There are small preview thumbnails working for other link posts but xkcd seems to be handled differently, possibly as carryover from S4R.

**Comment by laurencedawson** [comment] 2023-07-26 21:47
Fixed!

@geominorai you were right, they were still being treated as images

**Comment by geominorai** [comment] 2023-07-26 21:48
Thanks buddy.

**Closed by laurencedawson** 2023-07-26 21:47 UTC
