### ISSUE TITLE
App continually crashes if default post sorting is changed in settings

### ISSUE THREAD

**Issue by beerbaronstatic** [laurencedawson/sync-for-lemmy#154] opened 2023-07-29 11:17 UTC
**Describe the bug**  
After changing default post sort in settings when trying to view my feed the application closes. Cleared app data and same result.

**Steps to Reproduce**  
1. Go to settings
2. Click on post options
3. Change default post sort 
4. Try to go back to your feed

**Expected behavior
i should be able to see posts

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - Android: 14 beta 4.1
 - Sync version: beta 19
 - Lemmy Instance: midwest.social
 - Lemmy version: 0.18.3

**Comment by beerbaronstatic** [comment] 2023-07-30 01:44
[logcat.txt](https://github.com/laurencedawson/sync-for-lemmy/files/12208354/logcat.txt)

**Comment by laurencedawson** [comment] 2023-07-31 20:32
Does this happen with the beta 21?

**Comment by laurencedawson** [comment] 2023-08-01 11:34
Can't reproduce. Moving to post release milestone.

**Comment by th0mcat** [comment] 2023-08-02 19:30
Getting the same issue in Beta 24, signed in from midwest.social, Pixel 7 Pro.

[sync_logcat.txt](https://github.com/laurencedawson/sync-for-lemmy/files/12243989/sync_logcat.txt)

**Closed** 2023-08-23 00:25 UTC
Labels: bug
